version: '3.9'

services:
  tests:
    environment:
    - MAILGUN_API_KEY
    - MAILGUN_DOMAIN
    - SENDGRID_API_KEY
    - FCM_SERVER_KEY
    - FCM_SERVER_TO
    - TWILIO_ACCOUNT_SID
    - TWILIO_AUTH_TOKEN
    - TWILIO_TO
    - TWILIO_FROM
    - TELNYX_API_KEY
    - TELNYX_PUBLIC_KEY
    - APNS_AUTHKEY_8KVVCLA3HL
    - APNS_AUTH_ID
    - APNS_TEAM_ID
    - APNS_BUNDLE_ID
    - APNS_TO
    - MSG_91_SENDER_ID
    - MSG_91_AUTH_KEY
    - MSG_91_TO
    - MSG_91_FROM
    - TEST_EMAIL
    - TEST_FROM_EMAIL
    - VONAGE_API_KEY
    - VONAGE_API_SECRET
    - VONAGE_TO
    - VONAGE_FROM
    - PUSHER_INSTANCE_ID
    - PUSHER_SECRET_KEY
    - PUSHER_TO
    build:
      context: .
    volumes:
      - ./src:/usr/local/src/src
      - ./tests:/usr/local/src/tests
      - ./phpunit.xml:/usr/local/src/phpunit.xml

  maildev:
    image: appwrite/mailcatcher:1.0.0
    ports:
      - '10000:1080'

  request-catcher:
    image: appwrite/requestcatcher:1.0.0
    ports:
      - '10001:5000'
